name: nanoml
dependencies:
  - python=3.8
  - pyyaml
  - pytest-cov
  - pip:
    - scipy
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - scikit-learn
    - pytest
    - shap
    - xgboost
    - keras
    - tensorflow

